def hat():
    print('  *')
    print('  **    ')
    print('  * *  -\"I cast magic missile at the darkness!\"')
    print(' *****              -1d4')
    print(' *   *  @                     -1d4 ')
    print('   *   |      -1d4                         The Darkness        ') 
    print('  *****|      ')
    print(' * *   |                 -1d4 ')
    print('*  *   |')
    print('  * *  |   ') 
    print(' *   * |    ')
    print('*     * ')
